name: custom_calculator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

scripts: derry.yaml

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  flutter_localizations:
    sdk: flutter
  intl: any

  derry: ^1.5.0

  flutter_native_splash: ^2.3.4

  # logging
  logger: ^2.0.2+1

  # routing
  go_router: ^12.0.0

  # responsive
  device_preview: ^1.1.0
  sizer: ^2.0.15
  responsive_framework: ^1.1.1

  # model generator
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # asset generator
  flutter_gen: ^5.3.2

  # dependency injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # state management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2

  flutter_keyboard_visibility: ^5.4.1
  font_awesome_flutter: ^10.6.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  build_runner:
  flutter_gen_runner:
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.7.1
  go_router_builder: ^2.3.3
  injectable_generator: ^2.4.1

flutter_gen:
  output: lib/utils/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/animation/
    - assets/audio/
    - assets/font/
    - assets/image/
    - assets/json/
    - assets/video/